# Generated by Django 3.0.2 on 2020-01-26 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 26, 14, 40, 32, 452440)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbatch',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
