# Generated by Django 3.0.3 on 2020-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchwarning',
            name='new_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
