# Generated by Django 3.0.3 on 2020-02-20 17:16

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200218_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='original_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchwarning',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_warnings', to='api.ProductBatch'),
        ),
        migrations.CreateModel(
            name='ProductBatchArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('original_quantity', models.IntegerField()),
                ('leftover_quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('id_code', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archived_product_batches', to='api.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archived_store_batches', to='api.Store')),
            ],
            bases=(models.Model, api.models.ModelMixin),
        ),
    ]
