# Generated by Django 3.0.3 on 2020-02-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200220_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchwarning',
            name='product_batch_archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_warnings', to='api.ProductBatchArchive'),
        ),
        migrations.AlterField(
            model_name='batchwarning',
            name='product_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_warnings', to='api.ProductBatch'),
        ),
    ]
